### ISSUE TITLE
Add an alternative default theme that works with Sass

### ISSUE THREAD

**Issue by distriker** [morfy-cms/morfy#12]
Hi, I am adapting the default theme to Sass because I work in Sass more comfortably (and many people too). Nowadays, Sass is a very useful and powerful tool, and we shouldn't turn away.

I also changing some divs tags for another HTML5 tags, like in *blog.html*:

    <div class="container">
    <article class="container">

Bootstrap work mostly with the classes and ids, so change that not suppose a big problem.

I would like to know your opinion about that. I think in that like another default theme, like an "alternative" that work in Sass to the default theme.

Regards

**Comment by Awilum** [comment]
Closed for now.
