### ISSUE TITLE
Config Improvements

### ISSUE THREAD

**Issue by Awilum** [morfy-cms/morfy#26]
Config Improvements

/config/Morfy.php
/config/Fenom.php

**Comment by pafnuty** [comment]
На всякий случай присоединю сюда https://github.com/Awilum/morfy-cms/pull/31

**Comment by Awilum** [comment]
есть мысли о том то бы перейти на YAML ...

**Comment by pafnuty** [comment]
Думаю попробовать можно.
05.10.2015 0:44 пользователь "Sergey Romanenko" <notifications@github.com>
написал:

**Comment by maxicms** [comment]
yaml хорошо, но если будете использовать библиотеку от symfony то может быть имеет смысл рассмотреть вариант использовать вот это решение https://github.com/hassankhan/config оно тоже использует для работы библиотеку symfony, но дает очень гибкое использование форматов  PHP, INI, XML, JSON, and YML по факту это закроет все потребности в файлах конфигурации.

**Comment by Awilum** [comment]
Done for now.
Ready for Release!
