### ISSUE TITLE
Add new page header - published

### ISSUE THREAD

**Issue by Awilum** [morfy-cms/morfy#28]
```
published: true
```

By default, a page is **published**.
Valid values are **true** or **false**.

**Comment by tovic** [comment]
Why don&rsquo;t you just change the page file extension from `lorem-ipsum.md` another one. Example `lorem-ipsum.draft` ?

**Comment by Awilum** [comment]
thanks for your input! will think about this.

**Comment by bjorntheart** [comment]
How about separating drafts from published pages by putting then in a drafts folder?  Keeping the file extensions drafts/something.md would be kinder to editors supporting markdown styling

**Comment by Awilum** [comment]
closed for now
