### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by arcanedev-maroc** [morfy-cms/morfy#48]
Why not use `composer` instead the old `download the source from this page` ??

run `composer create-project morfy/morfy my-project` and voila !!

**Comment by dpertal** [comment]
no composer!
some server does not support so it is a shame!
I like being morfy simple!

**Comment by Awilum** [comment]
@dpertal this will not affect Morfy Simplicity :)
Implementation of Composer will give more advantage for developers.
Any way every new Morfy Release will have already downloaded and tested vendors libraries. So you didn't need to run Composer on your server :)

**Comment by Awilum** [comment]
Ticket created and added to milestone  https://github.com/morfy-cms/morfy/issues/51
