### ISSUE TITLE
Add PHP File for Custom Functions

### ISSUE THREAD

**Issue by tovic** [morfy-cms/morfy#7]
I want to add a PHP file called `fuctions.php` in the root so that we can use it to create some custom functions:

    morfy-cms
        - config.php
        - functions.php // <= this
        - index.php

https://github.com/tovic/morfy-cms/commit/11aa6e740e5a2cc01b60c471e51dbe505448cd57

**Comment by Awilum** [comment]
You can create a plugin with your custom functions and use it.
