### ISSUE TITLE
Fansoro's page bar doesn't refreshes itself

### ISSUE THREAD

**Issue by thermosflasche** [morfy-cms/morfy#79]
Basically when I add a new page/delete one, the top bar doesn't update the pages, thus giving 404 Error and pages missing. Please, fix this, I'm using the lastest Fansoro version.

**Comment by Awilum** [comment]
> the top bar doesn't update the pages

what is the TOP BAR ?

**Comment by thermosflasche** [comment]
The top bar is the bar that shows the disponible pages in the website, like Index, Contact, About, etc.

**Comment by Torsten-K** [comment]
I guess there is no autonav functionality in Fansoro. You have to edit _themes/[yourtheme]/partials/navigation.tpl_.
