### ISSUE TITLE
Undefined variable: pages_cache_id

### ISSUE THREAD

**Issue by Torsten-K** [morfy-cms/morfy#80]
On the home page of the blog area, I receive this error message:

> Notice: Undefined variable: pages_cache_id in /[…]/fansoro/fansoro/Pages.php on line 95

As I am no programmer, I have no idea what could be causing this error. I copied the default theme and changed some parts, but everything else works fine, so I think it is not my fault. Any idea?

**Comment by Awilum** [comment]
https://github.com/fansoro/fansoro/commit/b3beed150ac167e229f6aad09cd0b63157dd4375

**Comment by Torsten-K** [comment]
Thank you, the inserted code fixes the error. Will a bugfix version of Fansoro be published in the near future?

**Comment by Awilum** [comment]
this is a low prio bug, and it will not affect site on the production. its will be in some of the releases, but can't say any release day at the moment.
